version: '3'

#volumes:
#  nginx-data:

services:
  reverse-proxy-rtmp:
    build: .
    container_name: nginx-rtmp
    network_mode: "bridge"
#    ports:
#      - "80:80"
#      - "443:443"
#      - "1935:1935"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /nas:/nas
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    network_mode: "bridge"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "bridge"
#    ports:
#      - "32400:32400"
#      - "1900:1900/udp"
#      - "5353:5353/udp"
#      - "8324:8324/tcp"
#      - "32410:32410/udp"
#      - "32412:32412/udp"
#      - "32413:32413/udp"
#      - "32414:32414/udp"
#      - "32469:32469/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /nas/.config:/config
      - /nas/tv:/tv
      - /nas/movies:/movies
      - /nas/anime:/anime
      - /nas/cartoons:/cartoons
      - /nas/documentaries:/documentaries
      - /nas/family_photos:/family_photos
    restart: unless-stopped


#networks:
#  nginx-network:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.22.0.0/26
#    driver_opts:
#      com.docker.network.bridge.name: ngx-eth0
